global using FluentAssertions;
global using Heroes.Element.Models.AbilityTalents;
global using Heroes.LocaleText;
global using Heroes.XmlData;
global using Heroes.XmlData.StormData;
global using HeroesDataParser.Core;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using System.Xml.Linq;
