parameters:
  name: ''
  pool: ''

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    variables:
      config_debug: debug
      config_release: release
    strategy:
      matrix:
        Build_Debug:
          configuration: $(config_debug)
        Build_Release:
          configuration: $(config_release)
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET sdk'
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
        
    - powershell: |
        $cascexplorer = get-content CASCExplorer\CascLib\CascLib\CascLib.csproj
        $framework = $cascexplorer | select-string -pattern "<TargetFrameworks>"
        $framework -match "<TargetFrameworks>(?<content>.*)</TargetFrameworks>"
        $new = $matches['content'] -replace ".*;"
        $cascexplorer.replace($framework, "<TargetFrameworks>$new</TargetFrameworks>") | out-file CASCExplorer\CascLib\CascLib\CascLib.csproj
      displayName: Target Framework
     
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        includeNuGetOrg: true
      displayName: 'Restore'
      
    - script: dotnet build -c $(configuration) --no-restore  
      displayName: Build
 
    - script: dotnet test -c $(configuration) --no-build --logger trx --collect "Code coverage"
      displayName: Run tests
      
    - task: PublishTestResults@2
      displayName: Publish tests
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
