steps:
- script: |
    dotnet build -c Debug
    dotnet test -c Debug --no-build
  displayName: Debug Build and Test
- script: |
    dotnet build -c Release    
    dotnet test -c Release --no-build
  displayName: Release Build and Test
