name: Nuget Release

on: workflow_dispatch
  
jobs:
  deploy:
    uses: koliva8245/github.workflows/.github/workflows/nuget-release.yml@main
    with:
      artifacts-workflow: build.yml
      nuget-publish-env: Nuget Publish
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      nuget-user: ${{ secrets.NUGET_USER }}
