name: Nuget Release

on: workflow_dispatch

env:
  ARTIFACTS: ./artifacts

jobs:
  download-artifacts:
    uses: koliva8245/github.workflows/.github/workflows/nuget-release.yml@main
    with:
      artifacts-workflow: build.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  nuget-publish:
    runs-on: ubuntu-latest
    needs: download-artifacts
    permissions:
      id-token: write
    environment:
      name: Nuget Publish
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.ARTIFACTS }}

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet push
        run: dotnet nuget push ${{ env.ARTIFACTS }}/**/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
